version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(deps)'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
