packages:
  - '.'

overrides:
  '@sveltejs/kit>cookie': '>=0.7.0 <1.0.0'
  conventional-changelog-conventionalcommits: '>=8.0.0'
  glob: '>=10.5.0'
  minimatch: '>=10.2.4'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

minimumReleaseAge: 2880
