name: Release
on:
  workflow_run:
    workflows:
      - Check
    types:
      - completed

permissions:
  contents: read

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - run: corepack pnpm install
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo version=$(node -p "require('./package.json').version") >> "$GITHUB_OUTPUT"
        id: output-version
    outputs:
      version: ${{ steps.output-version.outputs.version }}
  build-image:
    name: build-image
    runs-on: ubuntu-latest
    needs: release
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          ref: v${{ needs.release.outputs.version }}
          fetch-depth: 0
      - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          file: ./d.build.Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: APP_MODE=prod
          push: true
          tags: ghcr.io/robin-w151/coffee-pal:latest,ghcr.io/robin-w151/coffee-pal:${{ needs.release.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
