name: Test
on:
  deployment_status:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      URL:
        type: string
        description: URL where the app is deployed

permissions:
  contents: read

jobs:
  test:
    name: test
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    if: ${{ github.event.deployment_status.state == 'success' || github.event_name != 'deployment_status' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - name: Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: npx playwright test
        env:
          TEST_BASE_URL: ${{ github.event.deployment_status.target_url || github.event.inputs.URL || 'https://coffee-pal.vercel.app' }}
      - name: Upload test report
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Upload playwright traces
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        if: ${{ !cancelled() && hashFiles('test-results/**/*') != '' }}
        with:
          name: playwright-traces
          path: test-results/
          retention-days: 30
